global:
  scrape_interval:     60s
  evaluation_interval: 60s

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 172.16.0.165:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['172.16.0.165:9090']
        labels:
          instance: prometheus

  - job_name: appserver
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.16.0.165:8000']
        labels:
          instance: appserver